# Generated by Django 2.2.1 on 2019-06-24 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=400)),
                ('apprances', models.CharField(default='', max_length=400)),
                ('goals', models.CharField(default='', max_length=400)),
                ('assists', models.CharField(default='', max_length=400)),
                ('redcards', models.CharField(default='', max_length=400)),
                ('yellowcards', models.CharField(default='', max_length=400)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=400)),
                ('age', models.CharField(default='', max_length=400)),
                ('position', models.CharField(default='', max_length=400)),
                ('club', models.CharField(default='', max_length=400)),
                ('nation', models.CharField(default='', max_length=400)),
                ('InfoId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='player_id', to='application.PlayerInfo')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
