# Generated by Django 2.2.1 on 2019-06-26 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(default='', max_length=400)),
                ('league', models.CharField(default='', max_length=400)),
                ('value', models.CharField(default='', max_length=400)),
                ('nation', models.CharField(default='', max_length=400)),
                ('continent', models.CharField(default='', max_length=400)),
            ],
            options={
                'ordering': ('teamName',),
            },
        ),
        migrations.RenameField(
            model_name='player',
            old_name='nation',
            new_name='apprances',
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='player',
            name='InfoId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='player_id', to='application.Team'),
        ),
        migrations.DeleteModel(
            name='PlayerInfo',
        ),
    ]
