# Generated by Django 2.2.1 on 2019-07-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190626_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='InfoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_id', to='application.Team'),
        ),
    ]
